import { useState } from 'react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { 
  HelpCircle, 
  Search, 
  MessageCircle, 
  Mail, 
  Phone,
  FileText,
  ExternalLink,
  Send
} from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';
import { toast } from 'sonner';

const faqs = [
  {
    question: 'How do I deposit funds?',
    answer: 'You can deposit funds by going to the Wallet section and clicking "Deposit". We support bank transfers to our accounts in Germany (EUR), Turkey (TRY), and Iran (IRR), as well as crypto deposits and PayPal.',
  },
  {
    question: 'What are the withdrawal limits?',
    answer: 'Withdrawal limits depend on your verification level. Unverified users have a daily limit of €500, while fully verified users can withdraw up to €50,000 per day. Large withdrawals may require additional verification.',
  },
  {
    question: 'How does the referral program work?',
    answer: 'Our referral program offers multi-level commissions: 10% on Level 1 (direct referrals), 5% on Level 2, and 2% on Level 3. You earn commissions from all trading fees generated by your referrals.',
  },
  {
    question: 'Is my data secure?',
    answer: 'Yes, we use industry-standard encryption (AES-256) for all data. We also implement 2FA, IP whitelisting, and advanced fraud detection. Your funds are stored in segregated cold wallets.',
  },
  {
    question: 'What cryptocurrencies do you support?',
    answer: 'We currently support Bitcoin (BTC), Ethereum (ETH), and Tether (USDT). More cryptocurrencies will be added based on user demand and regulatory compliance.',
  },
  {
    question: 'How long do withdrawals take?',
    answer: 'Crypto withdrawals are processed within 30 minutes. Bank transfers typically take 1-3 business days depending on your bank and location. Large withdrawals may require manual approval.',
  },
  {
    question: 'How does the AI Assistant work?',
    answer: 'Our AI Assistant provides market analysis using technical indicators like RSI, MACD, and Fibonacci retracements. It offers informational insights only and does not execute trades or provide financial advice.',
  },
  {
    question: 'What countries are supported?',
    answer: 'We operate in most European countries, Turkey, and select Middle Eastern regions. Some features may be restricted based on local regulations. Check our terms of service for a complete list.',
  },
];

export default function Help() {
  const { t } = useLanguage();
  const [searchQuery, setSearchQuery] = useState('');
  const [contactForm, setContactForm] = useState({ name: '', email: '', subject: '', message: '' });

  const filteredFaqs = faqs.filter(
    faq => 
      faq.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
      faq.answer.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const handleSubmitContact = () => {
    if (!contactForm.email || !contactForm.message) {
      toast.error('Please fill in all required fields');
      return;
    }
    toast.success('Message sent! We\'ll get back to you within 24 hours.');
    setContactForm({ name: '', email: '', subject: '', message: '' });
  };

  return (
    <MainLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="text-center max-w-2xl mx-auto">
          <h1 className="text-3xl font-bold gradient-text">{t('help')}</h1>
          <p className="text-muted-foreground mt-2">
            Find answers to common questions or contact our support team
          </p>
        </div>

        {/* Search */}
        <div className="max-w-xl mx-auto">
          <div className="relative">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
            <Input
              placeholder="Search for help..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-12 h-14 text-lg"
            />
          </div>
        </div>

        {/* Quick Links */}
        <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-4">
          <Card className="glass-panel hover:border-primary/50 cursor-pointer transition-all">
            <CardContent className="p-6 text-center">
              <div className="p-4 rounded-full bg-primary/20 w-fit mx-auto mb-3">
                <FileText className="h-6 w-6 text-primary" />
              </div>
              <h3 className="font-semibold">{t('documentation')}</h3>
              <p className="text-sm text-muted-foreground mt-1">Platform guides</p>
            </CardContent>
          </Card>

          <Card className="glass-panel hover:border-primary/50 cursor-pointer transition-all">
            <CardContent className="p-6 text-center">
              <div className="p-4 rounded-full bg-success/20 w-fit mx-auto mb-3">
                <MessageCircle className="h-6 w-6 text-success" />
              </div>
              <h3 className="font-semibold">Live Chat</h3>
              <p className="text-sm text-muted-foreground mt-1">24/7 support</p>
            </CardContent>
          </Card>

          <Card className="glass-panel hover:border-primary/50 cursor-pointer transition-all">
            <CardContent className="p-6 text-center">
              <div className="p-4 rounded-full bg-warning/20 w-fit mx-auto mb-3">
                <Mail className="h-6 w-6 text-warning" />
              </div>
              <h3 className="font-semibold">Email Support</h3>
              <p className="text-sm text-muted-foreground mt-1">support@samir.exchange</p>
            </CardContent>
          </Card>

          <Card className="glass-panel hover:border-primary/50 cursor-pointer transition-all">
            <CardContent className="p-6 text-center">
              <div className="p-4 rounded-full bg-secondary w-fit mx-auto mb-3">
                <Phone className="h-6 w-6" />
              </div>
              <h3 className="font-semibold">Phone Support</h3>
              <p className="text-sm text-muted-foreground mt-1">+49 30 1234567</p>
            </CardContent>
          </Card>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          {/* FAQ */}
          <Card className="glass-panel">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <HelpCircle className="h-5 w-5" />
                {t('faq')}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <Accordion type="single" collapsible className="w-full">
                {filteredFaqs.map((faq, index) => (
                  <AccordionItem key={index} value={`item-${index}`}>
                    <AccordionTrigger className="text-left">
                      {faq.question}
                    </AccordionTrigger>
                    <AccordionContent className="text-muted-foreground">
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
              
              {filteredFaqs.length === 0 && (
                <div className="text-center py-8 text-muted-foreground">
                  <HelpCircle className="h-12 w-12 mx-auto mb-3 opacity-50" />
                  <p>No results found for "{searchQuery}"</p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Contact Form */}
          <Card className="glass-panel">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Mail className="h-5 w-5" />
                {t('contactUs')}
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid sm:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-sm text-muted-foreground">Name</label>
                  <Input
                    value={contactForm.name}
                    onChange={(e) => setContactForm(f => ({ ...f, name: e.target.value }))}
                    placeholder="Your name"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm text-muted-foreground">Email *</label>
                  <Input
                    type="email"
                    value={contactForm.email}
                    onChange={(e) => setContactForm(f => ({ ...f, email: e.target.value }))}
                    placeholder="your@email.com"
                  />
                </div>
              </div>
              <div className="space-y-2">
                <label className="text-sm text-muted-foreground">Subject</label>
                <Input
                  value={contactForm.subject}
                  onChange={(e) => setContactForm(f => ({ ...f, subject: e.target.value }))}
                  placeholder="What's this about?"
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm text-muted-foreground">Message *</label>
                <Textarea
                  value={contactForm.message}
                  onChange={(e) => setContactForm(f => ({ ...f, message: e.target.value }))}
                  placeholder="Describe your issue or question..."
                  rows={5}
                />
              </div>
              <Button onClick={handleSubmitContact} className="w-full gap-2">
                <Send className="h-4 w-4" />
                Send Message
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </MainLayout>
  );
}
