import React, { createContext, useContext, useState, useCallback } from 'react';

export type Language = 'en' | 'de' | 'tr' | 'ru' | 'fa' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    exchange: 'Exchange',
    wallet: 'Wallet',
    markets: 'Markets',
    referrals: 'Referrals',
    aiAssistant: 'AI Assistant',
    security: 'Security',
    settings: 'Settings',
    help: 'Help',
    signOut: 'Sign Out',
    // Common
    search: 'Search markets, assets...',
    live: 'Live',
    account: 'Account',
    connectWallet: 'Connect Wallet',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    buy: 'Buy',
    sell: 'Sell',
    trade: 'Trade',
    balance: 'Balance',
    totalBalance: 'Total Balance',
    availableBalance: 'Available Balance',
    lockedBalance: 'Locked Balance',
    // Exchange
    fromCurrency: 'From',
    toCurrency: 'To',
    amount: 'Amount',
    youPay: 'You Pay',
    youReceive: 'You Receive',
    exchangeRate: 'Exchange Rate',
    fee: 'Fee',
    swapNow: 'Swap Now',
    // Wallet
    myWallets: 'My Wallets',
    addWallet: 'Add Wallet',
    walletAddress: 'Wallet Address',
    copyAddress: 'Copy Address',
    viewTransactions: 'View Transactions',
    // Markets
    price: 'Price',
    change24h: '24h Change',
    volume24h: '24h Volume',
    marketCap: 'Market Cap',
    high24h: '24h High',
    low24h: '24h Low',
    // Referrals
    referralProgram: 'Referral Program',
    yourReferralLink: 'Your Referral Link',
    copyLink: 'Copy Link',
    totalReferrals: 'Total Referrals',
    totalEarnings: 'Total Earnings',
    pendingRewards: 'Pending Rewards',
    referralTree: 'Referral Tree',
    // Security
    twoFactorAuth: 'Two-Factor Authentication',
    enable2FA: 'Enable 2FA',
    disable2FA: 'Disable 2FA',
    changePassword: 'Change Password',
    loginHistory: 'Login History',
    deviceManagement: 'Device Management',
    // Settings
    profileSettings: 'Profile Settings',
    notificationSettings: 'Notification Settings',
    languageSettings: 'Language Settings',
    themeSettings: 'Theme Settings',
    // Help
    faq: 'FAQ',
    support: 'Support',
    contactUs: 'Contact Us',
    documentation: 'Documentation',
    // AI
    askAI: 'Ask AI Assistant',
    aiAnalysis: 'AI Analysis',
    marketAnalysis: 'Market Analysis',
    technicalIndicators: 'Technical Indicators',
    tokens: 'Tokens',
    platformTokens: 'Platform Tokens',
    // Wallet Connection
    connectYourWallet: 'Connect Your Wallet',
    selectWallet: 'Select a wallet to connect',
    metamask: 'MetaMask',
    trustWallet: 'Trust Wallet',
    walletConnect: 'WalletConnect',
    paymentMethods: 'Payment Methods',
    visa: 'Visa Card',
    mastercard: 'MasterCard',
    paypal: 'PayPal',
    bankTransfer: 'Bank Transfer',
    admin: 'Admin Panel',
  },
  de: {
    dashboard: 'Dashboard',
    exchange: 'Börse',
    wallet: 'Wallet',
    markets: 'Märkte',
    referrals: 'Empfehlungen',
    aiAssistant: 'KI-Assistent',
    security: 'Sicherheit',
    settings: 'Einstellungen',
    help: 'Hilfe',
    signOut: 'Abmelden',
    search: 'Märkte, Assets suchen...',
    live: 'Live',
    account: 'Konto',
    connectWallet: 'Wallet verbinden',
    deposit: 'Einzahlen',
    withdraw: 'Auszahlen',
    buy: 'Kaufen',
    sell: 'Verkaufen',
    trade: 'Handeln',
    balance: 'Guthaben',
    totalBalance: 'Gesamtguthaben',
    availableBalance: 'Verfügbares Guthaben',
    lockedBalance: 'Gesperrtes Guthaben',
    fromCurrency: 'Von',
    toCurrency: 'Nach',
    amount: 'Betrag',
    youPay: 'Sie zahlen',
    youReceive: 'Sie erhalten',
    exchangeRate: 'Wechselkurs',
    fee: 'Gebühr',
    swapNow: 'Jetzt tauschen',
    myWallets: 'Meine Wallets',
    addWallet: 'Wallet hinzufügen',
    walletAddress: 'Wallet-Adresse',
    copyAddress: 'Adresse kopieren',
    viewTransactions: 'Transaktionen anzeigen',
    price: 'Preis',
    change24h: '24h Änderung',
    volume24h: '24h Volumen',
    marketCap: 'Marktkapitalisierung',
    high24h: '24h Hoch',
    low24h: '24h Tief',
    referralProgram: 'Empfehlungsprogramm',
    yourReferralLink: 'Ihr Empfehlungslink',
    copyLink: 'Link kopieren',
    totalReferrals: 'Gesamtempfehlungen',
    totalEarnings: 'Gesamteinnahmen',
    pendingRewards: 'Ausstehende Belohnungen',
    referralTree: 'Empfehlungsbaum',
    twoFactorAuth: 'Zwei-Faktor-Authentifizierung',
    enable2FA: '2FA aktivieren',
    disable2FA: '2FA deaktivieren',
    changePassword: 'Passwort ändern',
    loginHistory: 'Anmeldeverlauf',
    deviceManagement: 'Geräteverwaltung',
    profileSettings: 'Profileinstellungen',
    notificationSettings: 'Benachrichtigungseinstellungen',
    languageSettings: 'Spracheinstellungen',
    themeSettings: 'Design-Einstellungen',
    faq: 'FAQ',
    support: 'Support',
    contactUs: 'Kontakt',
    documentation: 'Dokumentation',
    askAI: 'KI-Assistent fragen',
    aiAnalysis: 'KI-Analyse',
    marketAnalysis: 'Marktanalyse',
    technicalIndicators: 'Technische Indikatoren',
    tokens: 'Token',
    platformTokens: 'Plattform-Token',
    connectYourWallet: 'Verbinden Sie Ihr Wallet',
    selectWallet: 'Wählen Sie ein Wallet',
    metamask: 'MetaMask',
    trustWallet: 'Trust Wallet',
    walletConnect: 'WalletConnect',
    paymentMethods: 'Zahlungsmethoden',
    visa: 'Visa-Karte',
    mastercard: 'MasterCard',
    paypal: 'PayPal',
    bankTransfer: 'Banküberweisung',
    admin: 'Admin-Panel',
  },
  tr: {
    dashboard: 'Panel',
    exchange: 'Borsa',
    wallet: 'Cüzdan',
    markets: 'Piyasalar',
    referrals: 'Referanslar',
    aiAssistant: 'AI Asistan',
    security: 'Güvenlik',
    settings: 'Ayarlar',
    help: 'Yardım',
    signOut: 'Çıkış',
    search: 'Piyasa, varlık ara...',
    live: 'Canlı',
    account: 'Hesap',
    connectWallet: 'Cüzdan Bağla',
    deposit: 'Yatır',
    withdraw: 'Çek',
    buy: 'Al',
    sell: 'Sat',
    trade: 'İşlem',
    balance: 'Bakiye',
    totalBalance: 'Toplam Bakiye',
    availableBalance: 'Kullanılabilir Bakiye',
    lockedBalance: 'Kilitli Bakiye',
    fromCurrency: 'Kimden',
    toCurrency: 'Kime',
    amount: 'Miktar',
    youPay: 'Ödeyeceğiniz',
    youReceive: 'Alacağınız',
    exchangeRate: 'Döviz Kuru',
    fee: 'Ücret',
    swapNow: 'Şimdi Değiştir',
    myWallets: 'Cüzdanlarım',
    addWallet: 'Cüzdan Ekle',
    walletAddress: 'Cüzdan Adresi',
    copyAddress: 'Adresi Kopyala',
    viewTransactions: 'İşlemleri Görüntüle',
    price: 'Fiyat',
    change24h: '24s Değişim',
    volume24h: '24s Hacim',
    marketCap: 'Piyasa Değeri',
    high24h: '24s Yüksek',
    low24h: '24s Düşük',
    referralProgram: 'Referans Programı',
    yourReferralLink: 'Referans Linkiniz',
    copyLink: 'Linki Kopyala',
    totalReferrals: 'Toplam Referanslar',
    totalEarnings: 'Toplam Kazanç',
    pendingRewards: 'Bekleyen Ödüller',
    referralTree: 'Referans Ağacı',
    twoFactorAuth: 'İki Faktörlü Doğrulama',
    enable2FA: '2FA Etkinleştir',
    disable2FA: '2FA Devre Dışı',
    changePassword: 'Şifre Değiştir',
    loginHistory: 'Giriş Geçmişi',
    deviceManagement: 'Cihaz Yönetimi',
    profileSettings: 'Profil Ayarları',
    notificationSettings: 'Bildirim Ayarları',
    languageSettings: 'Dil Ayarları',
    themeSettings: 'Tema Ayarları',
    faq: 'SSS',
    support: 'Destek',
    contactUs: 'İletişim',
    documentation: 'Dokümantasyon',
    askAI: 'AI\'ya Sor',
    aiAnalysis: 'AI Analizi',
    marketAnalysis: 'Piyasa Analizi',
    technicalIndicators: 'Teknik Göstergeler',
    tokens: 'Tokenlar',
    platformTokens: 'Platform Tokenları',
    connectYourWallet: 'Cüzdanınızı Bağlayın',
    selectWallet: 'Bir cüzdan seçin',
    metamask: 'MetaMask',
    trustWallet: 'Trust Wallet',
    walletConnect: 'WalletConnect',
    paymentMethods: 'Ödeme Yöntemleri',
    visa: 'Visa Kart',
    mastercard: 'MasterCard',
    paypal: 'PayPal',
    bankTransfer: 'Banka Transferi',
    admin: 'Yönetici Paneli',
  },
  ru: {
    dashboard: 'Панель',
    exchange: 'Обмен',
    wallet: 'Кошелек',
    markets: 'Рынки',
    referrals: 'Рефералы',
    aiAssistant: 'ИИ Ассистент',
    security: 'Безопасность',
    settings: 'Настройки',
    help: 'Помощь',
    signOut: 'Выход',
    search: 'Поиск рынков, активов...',
    live: 'Live',
    account: 'Аккаунт',
    connectWallet: 'Подключить кошелек',
    deposit: 'Депозит',
    withdraw: 'Вывод',
    buy: 'Купить',
    sell: 'Продать',
    trade: 'Торговать',
    balance: 'Баланс',
    totalBalance: 'Общий баланс',
    availableBalance: 'Доступный баланс',
    lockedBalance: 'Заблокированный баланс',
    fromCurrency: 'От',
    toCurrency: 'К',
    amount: 'Сумма',
    youPay: 'Вы платите',
    youReceive: 'Вы получите',
    exchangeRate: 'Курс обмена',
    fee: 'Комиссия',
    swapNow: 'Обменять',
    myWallets: 'Мои кошельки',
    addWallet: 'Добавить кошелек',
    walletAddress: 'Адрес кошелька',
    copyAddress: 'Копировать адрес',
    viewTransactions: 'Просмотр транзакций',
    price: 'Цена',
    change24h: 'Изменение 24ч',
    volume24h: 'Объем 24ч',
    marketCap: 'Рыночная капитализация',
    high24h: 'Макс. 24ч',
    low24h: 'Мин. 24ч',
    referralProgram: 'Реферальная программа',
    yourReferralLink: 'Ваша реферальная ссылка',
    copyLink: 'Копировать ссылку',
    totalReferrals: 'Всего рефералов',
    totalEarnings: 'Общий доход',
    pendingRewards: 'Ожидающие награды',
    referralTree: 'Дерево рефералов',
    twoFactorAuth: 'Двухфакторная аутентификация',
    enable2FA: 'Включить 2FA',
    disable2FA: 'Отключить 2FA',
    changePassword: 'Изменить пароль',
    loginHistory: 'История входов',
    deviceManagement: 'Управление устройствами',
    profileSettings: 'Настройки профиля',
    notificationSettings: 'Настройки уведомлений',
    languageSettings: 'Языковые настройки',
    themeSettings: 'Настройки темы',
    faq: 'FAQ',
    support: 'Поддержка',
    contactUs: 'Связаться с нами',
    documentation: 'Документация',
    askAI: 'Спросить ИИ',
    aiAnalysis: 'Анализ ИИ',
    marketAnalysis: 'Анализ рынка',
    technicalIndicators: 'Технические индикаторы',
    tokens: 'Токены',
    platformTokens: 'Токены платформы',
    connectYourWallet: 'Подключите кошелек',
    selectWallet: 'Выберите кошелек',
    metamask: 'MetaMask',
    trustWallet: 'Trust Wallet',
    walletConnect: 'WalletConnect',
    paymentMethods: 'Способы оплаты',
    visa: 'Visa карта',
    mastercard: 'MasterCard',
    paypal: 'PayPal',
    bankTransfer: 'Банковский перевод',
    admin: 'Панель администратора',
  },
  fa: {
    dashboard: 'داشبورد',
    exchange: 'صرافی',
    wallet: 'کیف پول',
    markets: 'بازارها',
    referrals: 'معرفی',
    aiAssistant: 'دستیار هوش مصنوعی',
    security: 'امنیت',
    settings: 'تنظیمات',
    help: 'راهنما',
    signOut: 'خروج',
    search: 'جستجوی بازارها، دارایی‌ها...',
    live: 'زنده',
    account: 'حساب کاربری',
    connectWallet: 'اتصال کیف پول',
    deposit: 'واریز',
    withdraw: 'برداشت',
    buy: 'خرید',
    sell: 'فروش',
    trade: 'معامله',
    balance: 'موجودی',
    totalBalance: 'موجودی کل',
    availableBalance: 'موجودی قابل استفاده',
    lockedBalance: 'موجودی قفل شده',
    fromCurrency: 'از',
    toCurrency: 'به',
    amount: 'مقدار',
    youPay: 'شما پرداخت می‌کنید',
    youReceive: 'شما دریافت می‌کنید',
    exchangeRate: 'نرخ تبدیل',
    fee: 'کارمزد',
    swapNow: 'تبدیل کن',
    myWallets: 'کیف پول‌های من',
    addWallet: 'افزودن کیف پول',
    walletAddress: 'آدرس کیف پول',
    copyAddress: 'کپی آدرس',
    viewTransactions: 'مشاهده تراکنش‌ها',
    price: 'قیمت',
    change24h: 'تغییرات ۲۴ ساعته',
    volume24h: 'حجم ۲۴ ساعته',
    marketCap: 'ارزش بازار',
    high24h: 'بیشترین ۲۴ ساعته',
    low24h: 'کمترین ۲۴ ساعته',
    referralProgram: 'برنامه معرفی',
    yourReferralLink: 'لینک معرفی شما',
    copyLink: 'کپی لینک',
    totalReferrals: 'کل معرفی‌ها',
    totalEarnings: 'کل درآمد',
    pendingRewards: 'پاداش‌های در انتظار',
    referralTree: 'درخت معرفی',
    twoFactorAuth: 'احراز هویت دو مرحله‌ای',
    enable2FA: 'فعال کردن 2FA',
    disable2FA: 'غیرفعال کردن 2FA',
    changePassword: 'تغییر رمز عبور',
    loginHistory: 'تاریخچه ورود',
    deviceManagement: 'مدیریت دستگاه‌ها',
    profileSettings: 'تنظیمات پروفایل',
    notificationSettings: 'تنظیمات اعلان‌ها',
    languageSettings: 'تنظیمات زبان',
    themeSettings: 'تنظیمات تم',
    faq: 'سوالات متداول',
    support: 'پشتیبانی',
    contactUs: 'تماس با ما',
    documentation: 'مستندات',
    askAI: 'از هوش مصنوعی بپرس',
    aiAnalysis: 'تحلیل هوش مصنوعی',
    marketAnalysis: 'تحلیل بازار',
    technicalIndicators: 'شاخص‌های تکنیکال',
    tokens: 'توکن‌ها',
    platformTokens: 'توکن‌های پلتفرم',
    connectYourWallet: 'کیف پول خود را متصل کنید',
    selectWallet: 'یک کیف پول انتخاب کنید',
    metamask: 'متامسک',
    trustWallet: 'تراست ولت',
    walletConnect: 'WalletConnect',
    paymentMethods: 'روش‌های پرداخت',
    visa: 'کارت ویزا',
    mastercard: 'مستر کارت',
    paypal: 'پی پال',
    bankTransfer: 'انتقال بانکی',
    admin: 'پنل مدیریت',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    exchange: 'تبادل',
    wallet: 'محفظة',
    markets: 'الأسواق',
    referrals: 'الإحالات',
    aiAssistant: 'مساعد الذكاء الاصطناعي',
    security: 'الأمان',
    settings: 'الإعدادات',
    help: 'مساعدة',
    signOut: 'تسجيل الخروج',
    search: 'البحث في الأسواق...',
    live: 'مباشر',
    account: 'الحساب',
    connectWallet: 'ربط المحفظة',
    deposit: 'إيداع',
    withdraw: 'سحب',
    buy: 'شراء',
    sell: 'بيع',
    trade: 'تداول',
    balance: 'الرصيد',
    totalBalance: 'الرصيد الإجمالي',
    availableBalance: 'الرصيد المتاح',
    lockedBalance: 'الرصيد المقفل',
    fromCurrency: 'من',
    toCurrency: 'إلى',
    amount: 'المبلغ',
    youPay: 'أنت تدفع',
    youReceive: 'أنت تستلم',
    exchangeRate: 'سعر الصرف',
    fee: 'الرسوم',
    swapNow: 'تبديل الآن',
    myWallets: 'محافظي',
    addWallet: 'إضافة محفظة',
    walletAddress: 'عنوان المحفظة',
    copyAddress: 'نسخ العنوان',
    viewTransactions: 'عرض المعاملات',
    price: 'السعر',
    change24h: 'التغير 24 ساعة',
    volume24h: 'الحجم 24 ساعة',
    marketCap: 'القيمة السوقية',
    high24h: 'الأعلى 24 ساعة',
    low24h: 'الأدنى 24 ساعة',
    referralProgram: 'برنامج الإحالة',
    yourReferralLink: 'رابط الإحالة الخاص بك',
    copyLink: 'نسخ الرابط',
    totalReferrals: 'إجمالي الإحالات',
    totalEarnings: 'إجمالي الأرباح',
    pendingRewards: 'المكافآت المعلقة',
    referralTree: 'شجرة الإحالة',
    twoFactorAuth: 'المصادقة الثنائية',
    enable2FA: 'تفعيل 2FA',
    disable2FA: 'تعطيل 2FA',
    changePassword: 'تغيير كلمة المرور',
    loginHistory: 'سجل تسجيل الدخول',
    deviceManagement: 'إدارة الأجهزة',
    profileSettings: 'إعدادات الملف الشخصي',
    notificationSettings: 'إعدادات الإشعارات',
    languageSettings: 'إعدادات اللغة',
    themeSettings: 'إعدادات المظهر',
    faq: 'الأسئلة الشائعة',
    support: 'الدعم',
    contactUs: 'اتصل بنا',
    documentation: 'التوثيق',
    askAI: 'اسأل الذكاء الاصطناعي',
    aiAnalysis: 'تحليل الذكاء الاصطناعي',
    marketAnalysis: 'تحليل السوق',
    technicalIndicators: 'المؤشرات الفنية',
    tokens: 'الرموز',
    platformTokens: 'رموز المنصة',
    connectYourWallet: 'قم بتوصيل محفظتك',
    selectWallet: 'اختر محفظة',
    metamask: 'ميتاماسك',
    trustWallet: 'تراست ولت',
    walletConnect: 'WalletConnect',
    paymentMethods: 'طرق الدفع',
    visa: 'بطاقة فيزا',
    mastercard: 'ماستركارد',
    paypal: 'باي بال',
    bankTransfer: 'تحويل بنكي',
    admin: 'لوحة الإدارة',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = useCallback((key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  }, [language]);

  const dir = language === 'fa' || language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      <div dir={dir}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
